/* Generated By:JJTree: Do not edit this line. ASTAffectation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAffectation extends SimpleNode {
  public ASTAffectation(int id) {
    super(id);
  }

  public ASTAffectation(Projet p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7d41621850003cf4d3f332f681dab6a2 (do not edit this line) */
