/* Generated By:JJTree: Do not edit this line. ASTBody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBody extends SimpleNode {
  public ASTBody(int id) {
    super(id);
  }

  public ASTBody(Projet p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=297bb783081ee252fab7d916b0387daf (do not edit this line) */
