/* Generated By:JJTree: Do not edit this line. ASTCorpsCondition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCorpsCondition extends SimpleNode {
  public ASTCorpsCondition(int id) {
    super(id);
  }

  public ASTCorpsCondition(Projet p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b63973dd99d4ac10dd5c3c27f0da81c0 (do not edit this line) */
