/* Generated By:JJTree: Do not edit this line. ASTcorpCC.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTcorpCC extends SimpleNode {
  public ASTcorpCC(int id) {
    super(id);
  }

  public ASTcorpCC(Projet p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=627792fc01c9217ce71259964aec7459 (do not edit this line) */
