/* Generated By:JJTree: Do not edit this line. ASTComment.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTComment extends SimpleNode {
  public ASTComment(int id) {
    super(id);
  }

  public ASTComment(Projet p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f54d414475f5195e2deb12d8d188fe9e (do not edit this line) */
