/* Generated By:JJTree: Do not edit this line. ASTDoWhile.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDoWhile extends SimpleNode {
  public ASTDoWhile(int id) {
    super(id);
  }

  public ASTDoWhile(Projet p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4733b16cce828658d62727cf9b515d29 (do not edit this line) */
