/* Generated By:JJTree: Do not edit this line. ASTDIncrementation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDIncrementation extends SimpleNode {
  public ASTDIncrementation(int id) {
    super(id);
  }

  public ASTDIncrementation(Projet p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f1ae6d23803ff9dc679f3c3638d2bc28 (do not edit this line) */
