/* Generated By:JJTree: Do not edit this line. ASTDecrementation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDecrementation extends SimpleNode {
  public ASTDecrementation(int id) {
    super(id);
  }

  public ASTDecrementation(Projet p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6691badd46413071cea52edad42b97d5 (do not edit this line) */
