/* Generated By:JJTree: Do not edit this line. ASTExpressionArithmetique.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpressionArithmetique extends SimpleNode {
  public ASTExpressionArithmetique(int id) {
    super(id);
  }

  public ASTExpressionArithmetique(Projet p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dcb53a7b259309b3563042ff25917329 (do not edit this line) */
