/* Generated By:JJTree: Do not edit this line. ASTLogicalOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLogicalOperator extends SimpleNode {
  public ASTLogicalOperator(int id) {
    super(id);
  }

  public ASTLogicalOperator(Projet p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bd0ea2baf66cbde4285ccf3a87daa765 (do not edit this line) */
