/* Generated By:JJTree: Do not edit this line. ASTProduitArithmetique.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTProduitArithmetique extends SimpleNode {
  public ASTProduitArithmetique(int id) {
    super(id);
  }

  public ASTProduitArithmetique(Projet p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a8114d55a65a2faa9d8aeb8c730ab90a (do not edit this line) */
