/* Generated By:JJTree: Do not edit this line. ASTType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTType extends SimpleNode {
	
	String valeur;
	
  public ASTType(int id) {
    super(id);
  }

  public ASTType(Projet p, int id) {
    super(p, id);
  }

public void setValeur(String val){
		valeur = val;
	}

	public String toString(){
		return "Type :"+valeur;
	}
	
	public String getValeur(){
		return valeur;
	}
}
/* JavaCC - OriginalChecksum=958915780881e6b2859ace5373f77632 (do not edit this line) */
