/* Generated By:JJTree: Do not edit this line. ASTvoid.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTvoid extends SimpleNode {
  public ASTvoid(int id) {
    super(id);
  }

  public ASTvoid(Projet p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=be773f5f4b750c80416adf5ff9a54dc1 (do not edit this line) */
