/* Generated By:JavaCC: Do not edit this line. ProjetTreeConstants.java Version 5.0 */
public interface ProjetTreeConstants
{
  public int JJTVOID = 0;
  public int JJTAFFICHAGELEXEME = 1;
  public int JJTCODE = 2;
  public int JJTMAIN = 3;
  public int JJTCONDITION = 4;
  public int JJTAFFECTATION = 5;
  public int JJTFOR = 6;
  public int JJTEXPRESSIONARITHMETIQUE = 7;
  public int JJTPRODUITARITHMETIQUE = 8;
  public int JJTENTIER = 9;
  public int JJTEXPRESSIONBOOLEENNE = 10;
  public int JJTIDENT = 11;


  public String[] jjtNodeName = {
    "void",
    "AffichageLexeme",
    "Code",
    "Main",
    "Condition",
    "Affectation",
    "For",
    "ExpressionArithmetique",
    "ProduitArithmetique",
    "Entier",
    "ExpressionBooleenne",
    "Ident",
  };
}
/* JavaCC - OriginalChecksum=a78eecf5d8f64d3c94d8fc82aad3d6cf (do not edit this line) */
