/* Generated By:JJTree: Do not edit this line. ASTBoucles.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBoucles extends SimpleNode {
  public ASTBoucles(int id) {
    super(id);
  }

  public ASTBoucles(Projet p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=984fdeedf75cd3b81d01e0614cb1db2e (do not edit this line) */
