/* Generated By:JJTree: Do not edit this line. ASTConditionSigne.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTConditionSigne extends SimpleNode {
  public ASTConditionSigne(int id) {
    super(id);
  }

  public ASTConditionSigne(Projet p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5e6a079500e1bd9314398d7cb44fd950 (do not edit this line) */
