/* Generated By:JJTree: Do not edit this line. ASTCommentaire.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCommentaire extends SimpleNode {
  public ASTCommentaire(int id) {
    super(id);
  }

  public ASTCommentaire(Projet p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d346c0bf1bb5fca9633536801b69ee27 (do not edit this line) */
