/* Generated By:JJTree: Do not edit this line. ASTCode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCode extends SimpleNode {
  public ASTCode(int id) {
    super(id);
  }

  public ASTCode(Projet p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b71f1c021945af5733d98e699b23530a (do not edit this line) */
