/* Generated By:JJTree: Do not edit this line. ASTDecIncrementation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDecIncrementation extends SimpleNode {
  public ASTDecIncrementation(int id) {
    super(id);
  }

  public ASTDecIncrementation(Projet p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8f9e57237acd0ab5e1e9991490c2c756 (do not edit this line) */
