/* Generated By:JJTree: Do not edit this line. ASTEntier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEntier extends SimpleNode {
  public ASTEntier(int id) {
    super(id);
  }

  public ASTEntier(Projet p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c875e9475b97369935d3e4cb6cb2ec9f (do not edit this line) */
