/* Generated By:JJTree: Do not edit this line. ASTFor.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFor extends SimpleNode {
  public ASTFor(int id) {
    super(id);
  }

  public ASTFor(Projet p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a79a21edf60e852fb5e526e027daaf13 (do not edit this line) */
