/* Generated By:JJTree: Do not edit this line. ASTInclude.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTInclude extends SimpleNode {
  public ASTInclude(int id) {
    super(id);
  }

  public ASTInclude(Projet p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=63a0a3bc22d8cead50d2f3ed8fb73d17 (do not edit this line) */
