/* Generated By:JJTree: Do not edit this line. ASTinclude.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTinclude extends SimpleNode {
  public ASTinclude(int id) {
    super(id);
  }

  public ASTinclude(Projet p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=91ee5a51a37e079ef866b7e3daf12126 (do not edit this line) */
