/* Generated By:JJTree: Do not edit this line. ASTIncrementation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIncrementation extends SimpleNode {
  public ASTIncrementation(int id) {
    super(id);
  }

  public ASTIncrementation(Projet p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ff902e043e040007ab04929730cc7375 (do not edit this line) */
