/* Generated By:JJTree: Do not edit this line. ASTIdent.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIdent extends SimpleNode {
  public ASTIdent(int id) {
    super(id);
  }

  public ASTIdent(Projet p, int id) {
    super(p, id);
  }

 
}
/* JavaCC - OriginalChecksum=347901ef5e16118c7fd0cb5e69d18703 (do not edit this line) */
