/* Generated By:JJTree: Do not edit this line. ASTMain.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMain extends SimpleNode {
  public ASTMain(int id) {
    super(id);
  }

  public ASTMain(Projet p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e4f07415032800e9cbe91ad482904b3e (do not edit this line) */
