/* Generated By:JJTree: Do not edit this line. ASTParameters.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTParameters extends SimpleNode {
  public ASTParameters(int id) {
    super(id);
  }

  public ASTParameters(Projet p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2525a0eaf8019ccdb1c1f4108f23b2a8 (do not edit this line) */
