/* Generated By:JJTree: Do not edit this line. ASTSwitch.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSwitch extends SimpleNode {
  public ASTSwitch(int id) {
    super(id);
  }

  public ASTSwitch(Projet p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=672762fbae6babd6de9ea27ad4deb224 (do not edit this line) */
