/* Generated By:JavaCC: Do not edit this line. ProjetTreeConstants.java Version 5.0 */
public interface ProjetTreeConstants
{
  public int JJTVOID = 0;
  public int JJTAFFICHAGELEXEME = 1;
  public int JJTCODE = 2;
  public int JJTOPERATOR = 3;
  public int JJTLOGICALOPERATOR = 4;
  public int JJTINCLUDE = 5;
  public int JJTCOMMENTAIRE = 6;
  public int JJTTYPE = 7;
  public int JJTFUNCTION = 8;
  public int JJTPARAMETERS = 9;
  public int JJTCONDITIONSIGNE = 10;
  public int JJTCORPCC = 11;
  public int JJTCONDITION = 12;
  public int JJTAFFECTATION = 13;
  public int JJTBOUCLES = 14;
  public int JJTDINCREMENTATION = 15;
  public int JJTFOR = 16;
  public int JJTWHILE = 17;
  public int JJTDOWHILE = 18;
  public int JJTSWITCH = 19;
  public int JJTEXPRESSIONARITHMETIQUE = 20;
  public int JJTPRODUITARITHMETIQUE = 21;
  public int JJTENTIER = 22;
  public int JJTEXPRESSIONBOOLEENNE = 23;
  public int JJTIDENT = 24;


  public String[] jjtNodeName = {
    "void",
    "AffichageLexeme",
    "Code",
    "Operator",
    "LogicalOperator",
    "Include",
    "Commentaire",
    "Type",
    "Function",
    "Parameters",
    "ConditionSigne",
    "corpCC",
    "Condition",
    "Affectation",
    "Boucles",
    "DIncrementation",
    "For",
    "While",
    "DoWhile",
    "Switch",
    "ExpressionArithmetique",
    "ProduitArithmetique",
    "Entier",
    "ExpressionBooleenne",
    "Ident",
  };
}
/* JavaCC - OriginalChecksum=e620735ba6c5150129e97a8a4a8dff11 (do not edit this line) */
