/* Generated By:JJTree&JavaCC: Do not edit this line. ProjetConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ProjetConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int IF = 6;
  /** RegularExpression Id. */
  int FOR = 7;
  /** RegularExpression Id. */
  int THEN = 8;
  /** RegularExpression Id. */
  int ELSE = 9;
  /** RegularExpression Id. */
  int INT = 10;
  /** RegularExpression Id. */
  int CHAR = 11;
  /** RegularExpression Id. */
  int FLOAT = 12;
  /** RegularExpression Id. */
  int LONG = 13;
  /** RegularExpression Id. */
  int PARAL = 14;
  /** RegularExpression Id. */
  int PARAR = 15;
  /** RegularExpression Id. */
  int ACCOL = 16;
  /** RegularExpression Id. */
  int ACCOR = 17;
  /** RegularExpression Id. */
  int EGAL = 18;
  /** RegularExpression Id. */
  int PVIRG = 19;
  /** RegularExpression Id. */
  int POINT = 20;
  /** RegularExpression Id. */
  int NOT = 21;
  /** RegularExpression Id. */
  int TRUE = 22;
  /** RegularExpression Id. */
  int FALSE = 23;
  /** RegularExpression Id. */
  int PLUS = 24;
  /** RegularExpression Id. */
  int MINUS = 25;
  /** RegularExpression Id. */
  int MULT = 26;
  /** RegularExpression Id. */
  int DIV = 27;
  /** RegularExpression Id. */
  int INTEGER = 28;
  /** RegularExpression Id. */
  int IDENT = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"main\"",
    "\"if\"",
    "\"for\"",
    "\"then\"",
    "\"else\"",
    "\"int\"",
    "\"char\"",
    "\"float\"",
    "\"long\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\";\"",
    "\".\"",
    "\"!\"",
    "\"true\"",
    "\"false\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<INTEGER>",
    "<IDENT>",
  };

}
